# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d6a8b20a76e5a98c02cd7f0a9d048490ac04df1c9d19c0038d73bc9af2115c237edfc2482bcda4189c13f3eced4a990c41aa4e2042b24b5b2a970a7da052f1fb

test:
  secret_key_base: e849d5764672e9cb6ba17fc850eb9e4293ab60a33a2c772e5a783ab68b0912c17fc5b5fd8314230195d1f7a9b9a4f2ce59ccdbd2682dda787bdfd8852f14e690

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
